"""add_target_user_fields_to_role_switch_links

Revision ID: d063884cd482
Revises: 61f3f3daef1e
Create Date: 2025-08-04 23:30:22.595400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd063884cd482'
down_revision: Union[str, Sequence[str], None] = '61f3f3daef1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role_switch_links', sa.Column('target_user_id', sa.UUID(), nullable=True))
    op.add_column('role_switch_links', sa.Column('target_user_name', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'role_switch_links', 'users', ['target_user_id'], ['id'])
    op.alter_column('users', 'telegram_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # Убираем проблемную строку - ограничение не существует
    # op.drop_constraint(op.f('users_telegram_id_key'), 'users', type_='unique')
    # Убираем создание индекса - он уже существует
    # op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.create_unique_constraint(op.f('users_telegram_id_key'), 'users', ['telegram_id'])
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'telegram_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.drop_constraint(None, 'role_switch_links', type_='foreignkey')
    op.drop_column('role_switch_links', 'target_user_name')
    op.drop_column('role_switch_links', 'target_user_id')
    # ### end Alembic commands ###
