"""Refactor models

Revision ID: 132483303285
Revises: 587ae46e94c8
Create Date: 2025-10-15 18:52:46.980541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '132483303285'
down_revision: Union[str, None] = '587ae46e94c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('user_id', sa.UUID(), nullable=False))
    op.drop_index('ix_notifications_recipient_telegram_id', table_name='notifications')
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.drop_column('notifications', 'recipient_telegram_id')
    op.add_column('user_notification_settings', sa.Column('user_id', sa.UUID(), nullable=False))
    op.add_column('user_notification_settings', sa.Column('chat_id', sa.BigInteger(), nullable=True))
    op.drop_constraint('user_notification_settings_user_telegram_id_key', 'user_notification_settings', type_='unique')
    op.create_index(op.f('ix_user_notification_settings_chat_id'), 'user_notification_settings', ['chat_id'], unique=False)
    op.create_index(op.f('ix_user_notification_settings_user_id'), 'user_notification_settings', ['user_id'], unique=True)
    op.drop_column('user_notification_settings', 'user_telegram_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_notification_settings', sa.Column('user_telegram_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_user_notification_settings_user_id'), table_name='user_notification_settings')
    op.drop_index(op.f('ix_user_notification_settings_chat_id'), table_name='user_notification_settings')
    op.create_unique_constraint('user_notification_settings_user_telegram_id_key', 'user_notification_settings', ['user_telegram_id'])
    op.drop_column('user_notification_settings', 'chat_id')
    op.drop_column('user_notification_settings', 'user_id')
    op.add_column('notifications', sa.Column('recipient_telegram_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.create_index('ix_notifications_recipient_telegram_id', 'notifications', ['recipient_telegram_id'], unique=False)
    op.drop_column('notifications', 'user_id')
    # ### end Alembic commands ###
