"""add invite_token to group_invitations

Revision ID: 2727f4a2dc11
Revises: b22cdfba004a
Create Date: 2025-08-12 20:29:54.905894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2727f4a2dc11'
down_revision: Union[str, None] = 'b22cdfba004a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_invitations', sa.Column('invite_token', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'group_invitations', ['invite_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'group_invitations', type_='unique')
    op.drop_column('group_invitations', 'invite_token')
    # ### end Alembic commands ###
