"""delete data from model

Revision ID: b22cdfba004a
Revises: 6bb533182160
Create Date: 2025-08-10 18:30:23.528457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b22cdfba004a'
down_revision: Union[str, None] = '6bb533182160'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'duration_minutes')
    op.drop_column('groups', 'schedule_time')
    op.drop_column('groups', 'schedule_days')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('schedule_days', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('groups', sa.Column('schedule_time', sa.VARCHAR(length=5), autoincrement=False, nullable=True))
    op.add_column('groups', sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
