version: "3.9"

services:
  bff:
    build: .
    container_name: bff-service
    ports:
      - "8000:8000"
    volumes:
      - ./bff:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
