"""update teacher model remove duplication

Revision ID: 3517f91ae524
Revises: bc6472ddb622
Create Date: 2025-07-28 22:21:03.846260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3517f91ae524'
down_revision: Union[str, None] = 'bc6472ddb622'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Удаляем foreign key constraint
    op.drop_constraint('teacher_languages_teacher_id_fkey', 'teacher_languages', type_='foreignkey')

    # Удаляем дублированные поля
    op.drop_column('teachers', 'phone_number')
    op.drop_column('teachers', 'email')
    op.drop_column('teachers', 'is_active')
    op.drop_column('teachers', 'is_verified')
    op.drop_column('teachers', 'is_available')
    op.drop_column('teachers', 'created_at')
    op.drop_column('teachers', 'updated_at')

    # Изменяем тип id с INTEGER на UUID
    op.execute('ALTER TABLE teachers ALTER COLUMN id DROP DEFAULT')
    op.execute('ALTER TABLE teachers ALTER COLUMN id TYPE UUID USING gen_random_uuid()')
    op.execute('ALTER TABLE teachers ALTER COLUMN id SET DEFAULT gen_random_uuid()')

    # Добавляем новое поле для почасовой ставки
    op.add_column('teachers', sa.Column('hourly_rate', sa.Float(), nullable=True))

    # Удаляем таблицу teacher_languages (будет пересоздана позже если нужно)
    op.drop_table('teacher_languages')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('teachers', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('teachers', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('teachers', sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('teachers', sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('teachers', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('teachers', sa.Column('is_available', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('teachers', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('teachers', 'hourly_rate')
    op.alter_column('teacher_languages', 'teacher_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
