"""remove TeacherDaySchedule model

Revision ID: 12b764b262a4
Revises: 471c51a6f8c3
Create Date: 2025-08-21 20:46:24.377408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '12b764b262a4'
down_revision: Union[str, None] = '471c51a6f8c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_teacher_day_schedules_id', table_name='teacher_day_schedules')
    op.drop_table('teacher_day_schedules')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher_day_schedules',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('teacher_telegram_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('start_time', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('end_time', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('booked_slots', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='teacher_day_schedules_pkey')
    )
    op.create_index('ix_teacher_day_schedules_id', 'teacher_day_schedules', ['id'], unique=False)
    # ### end Alembic commands ###
