"""Initial schema

Revision ID: 471c51a6f8c3
Revises: 
Create Date: 2025-08-10 14:31:34.697327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '471c51a6f8c3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher_day_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.String(length=5), nullable=False),
    sa.Column('end_time', sa.String(length=5), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('booked_slots', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teacher_day_schedules_id'), 'teacher_day_schedules', ['id'], unique=False)
    op.create_table('teacher_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.String(length=5), nullable=False),
    sa.Column('end_time', sa.String(length=5), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teacher_schedules_id'), 'teacher_schedules', ['id'], unique=False)
    op.create_table('teacher_unavailable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teacher_unavailable_id'), 'teacher_unavailable', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teacher_unavailable_id'), table_name='teacher_unavailable')
    op.drop_table('teacher_unavailable')
    op.drop_index(op.f('ix_teacher_schedules_id'), table_name='teacher_schedules')
    op.drop_table('teacher_schedules')
    op.drop_index(op.f('ix_teacher_day_schedules_id'), table_name='teacher_day_schedules')
    op.drop_table('teacher_day_schedules')
    # ### end Alembic commands ###
