"""add special day model

Revision ID: ba2ba44c4ea3
Revises: 12b764b262a4
Create Date: 2025-08-22 16:54:43.452913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba2ba44c4ea3'
down_revision: Union[str, None] = '12b764b262a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher_special_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.String(length=5), nullable=False),
    sa.Column('end_time', sa.String(length=5), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teacher_special_days_id'), 'teacher_special_days', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teacher_special_days_id'), table_name='teacher_special_days')
    op.drop_table('teacher_special_days')
    # ### end Alembic commands ###
