version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: telegram-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./:/src   # Чтобы при разработке можно было менять код без пересборки
    command: python src/main.py
